---

kafka_server_node_id: 1
kafka_server_process_roles: broker
kafka_server_listeners: "PLAINTEXT://{{ ansible_fqdn }}:{{ kafka_broker_port }}"
kafka_server_advertised_listeners: "PLAINTEXT://{{ ansible_fqdn }}:{{ kafka_broker_port }}"
